name = "MajoranaFunctions"
uuid = "bb27fe77-b015-4b10-a214-8ec769d9e422"
authors = ["williamesamuelson <william.samuelson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumDots = "312194fd-fec5-4b07-ba1c-a40d7013a56a"
